name:  Run a Windows executable
on:  
  pull_request:
    types: [closed]
env:
  PR_NUMBER: ${{ github.event.number }}
  GITHUB_ACTOR: ${{ github.actor }}
  GITHUB_EVENT_NAME: ${{ github.event_name }}
  
jobs:
  build:
    if: github.event.pull_request.merged == true
    name:  Create CR
    runs-on: windows-latest
    
    steps:
      - uses:  actions/checkout@v1
      - name:  Create new ServiceNow standard change request
        run: |
          echo "The GitHub Action Secret will be masked: "
          echo ${{ secrets.7 }}
          echo "Trick to echo GitHub Action Secret:  "
          echo ${{secrets.7 }} | sed 's/ ./& /g'  
          action/imc.exe
      
    
